name: metapathways
channels:
  - conda-forge
  - bioconda
  - hallamlab
dependencies:
  - metapathways
  - python=3.10
  - snakemake
  - curl
  - ncurses
  - pysam
  - pybedtools
  - coverm
  - blast
  - prodigal
  - bwa
  - samtools
  - barrnap
  - trnascan-se
  - subread
  - mmseqs2
  - bmge
  - hmmer
  - epa-ng
  - raxml-ng
  - fasttree
  - git
  - requests
  - mafft
