channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-build
  - boa
  - anaconda-client
  - conda-verify
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    - twine
    - build
    - git+https://bitbucket.org/tomeraltman/camelot-frs@dev#egg=camelot-frs
    - git+https://github.com/hallamlab/MAGSplitter.git@main
