name: metapathways
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - snakemake=7.32.4
  - pulp=2.7.0
  - setuptools<81
  - curl
  - ncurses
  - pysam
  - cython
  - prodigal
  - pprodigal
  - pybedtools
  - coverm
  - blast
  - bwa
  - samtools
  - barrnap
  - trnascan-se
  - subread
  - tqdm
  - pyfastx
  - pandas
  - sexpdata
  - html2text
  - scipy
  - peppy
  - pip
