name: metapathways
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - nextflow>=25.10,<27
  - apptainer>=1.3,<2
  - setuptools>=83,<85
  - urllib3>=2.8.0,<3
  - curl
  - wget
  - ncurses
  - pysam
  - cython
  - prodigal
  - pprodigal
  - pybedtools
  - coverm
  - blast
  - bwa
  - samtools
  - barrnap
  - trnascan-se
  - subread
  - tqdm
  - pyfastx
  - pandas
  - sexpdata
  - html2text
  - scipy
  - peppy
