__author__ = "Ryan J. McLaughlin, Kishori M Konwar [add all others]"
__version__ = "3.5.0.dev46"
__maintainer__ = "Ryan J. McLaughlin"
__contact__ = "mcglock@student.ubc.ca"
__status__ = "Development"
__copyright__ = "Copyright 2024, MetaPathways"
__license__ = "MIT"