## -*- python -*-

#### Snakemake file for MetaPathways

## This is currently used for orchestrating the staging of reference databases used by end-users.
## In the future this will be used to integrate new functionality into MetaPathways.

### Local Definitions:

## User-configurations are set in the config YAML file, not in this Snakemake file:
#configfile: "snakemake_config.yaml"

## Database versions:
arb_release = "138.1"

## Mapping files to URL prefixes:
file2url_prefix = {}
file2url_prefix['SILVA_' + arb_release + '_LSUParc_tax_silva.fasta.gz'] = 'https://www.arb-silva.de/fileadmin/silva_databases/release_' + arb_release + '/Exports'
file2url_prefix['SILVA_' + arb_release + '_SSUParc_tax_silva.fasta.gz'] = 'https://www.arb-silva.de/fileadmin/silva_databases/release_' + arb_release + '/Exports'

hosted_functional_dbs = ["cazy",
                         "kegg",
                         "metacyc"]

third_party_functional_dbs = ["refseq"]

functional_db_names = ['cazy-2020-06-01',
                       'kegg-uniprot-2018-12-20',
                       'metacyc-2020-08-10',
                       'uniprot_sprot']

taxonomic_db_names = ['SILVA_138.1_LSURef_tax_silva',
                      'SILVA_138.1_SSURef_tax_silva']

### DB Staging Rules:
rule create_names_txt_files:
    input:
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt',
               func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt',
               tax_db = taxonomic_db_names),
        config['ref_db_dir'] + '/functional/formatted/refseq_protein-names.txt'
    group: "names-group"



rule stage_blast_full:
    input:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.ndb', arb_release=arb_release),
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.pdb',
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.pdb',
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.pdb',
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.pdb',
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.26.psq'
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt',
               func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt',
               tax_db = taxonomic_db_names),

        
rule stage_blast_lite:
    input:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.ndb', arb_release=arb_release),
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.pdb',
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.pdb',
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.pdb',
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.pdb'
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt',
               func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt',
               tax_db = taxonomic_db_names)

# silva is still blast...
rule stage_fast_lite:
    input:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.ndb', arb_release=arb_release),
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.prj',
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.prj',
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.prj',
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.prj',
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt',
               func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt',
               tax_db = taxonomic_db_names)

rule stage_fast_full:
    input:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.prj', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.prj', arb_release=arb_release),
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.prj',
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.prj',
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.prj',
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.prj',
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.prj',
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt',
               func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt',
               tax_db = taxonomic_db_names),
        config['ref_db_dir'] + '/functional/formatted/refseq_protein-names.txt'

        
rule download_only:
    input:
        config["ref_db_dir"] + '/taxonomic/SILVA_' + arb_release + '_SSURef_tax_silva',
        config["ref_db_dir"] + '/functional/uniprot_sprot',
        config["ref_db_dir"] + '/functional/kegg-uniprot-2018-12-20',
        config["ref_db_dir"] + '/functional/cazy-2020-06-01',
        config["ref_db_dir"] + '/functional/metacyc-2020-08-10',
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.26.psq'

rule create_dirs_local_files:
    params:
        target_dir = config["ref_db_dir"],
        pkg_dir    = config["pkg_dir"]
    output:
        config["ref_db_dir"] + '/Dsignal'
    shell:
        """
        mkdir -p {params.target_dir}/functional/formatted
        mkdir -p {params.target_dir}/taxonomic/formatted
        cp {params.pkg_dir}/tests/data/ref_data/Dsignal {params.target_dir}/
        cp {params.pkg_dir}/tests/data/ref_data/TPCsignal {params.target_dir}/
        ## Stage Functional Categories Files:
        cp -R {params.pkg_dir}/tests/data/ref_data/functional_categories {params.target_dir}/
        cp -R {params.pkg_dir}/tests/data/ref_data/ncbi_tree {params.target_dir}/
        """
        
rule fetch_silva_db:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config["ref_db_dir"],
        arb_release = arb_release
    output:
        ssu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_SSURef_tax_silva', arb_release=arb_release),
        lsu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_LSURef_tax_silva', arb_release=arb_release)
    shell:
        """
        cd {params.target_dir}/taxonomic
        wget -O SILVA_{params.arb_release}_LSURef_tax_silva.gz https://www.arb-silva.de/fileadmin/silva_databases/release_{params.arb_release}/Exports/SILVA_{params.arb_release}_LSURef_tax_silva.fasta.gz
        wget -O SILVA_{params.arb_release}_SSURef_tax_silva.gz https://www.arb-silva.de/fileadmin/silva_databases/release_{params.arb_release}/Exports/SILVA_{params.arb_release}_SSURef_tax_silva.fasta.gz
        gunzip {output.ssu_silva_file}.gz
        gunzip {output.lsu_silva_file}.gz
        """

rule make_silva_blast_db:
    input:
        ssu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_SSURef_tax_silva', arb_release=arb_release),
        lsu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_LSURef_tax_silva', arb_release=arb_release)
    params:
        target_dir = config["ref_db_dir"],
        arb_release = arb_release
    output:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.ndb', arb_release=arb_release)
    shell:
        """
        cd {params.target_dir}/taxonomic
        makeblastdb -in SILVA_{arb_release}_LSURef_tax_silva -dbtype nucl -parse_seqids -out formatted/SILVA_{arb_release}_LSURef_tax_silva
        makeblastdb -in SILVA_{arb_release}_SSURef_tax_silva -dbtype nucl -parse_seqids -out formatted/SILVA_{arb_release}_SSURef_tax_silva
        """

# fast doesn't work well with nucl
# rule make_silva_fast_db:
#     input:
#         ssu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_SSURef_tax_silva', arb_release=arb_release),
#         lsu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_LSURef_tax_silva', arb_release=arb_release)
#     params:
#         target_dir = config["ref_db_dir"],
#         arb_release = arb_release
#     output:
#         expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_tax_silva.prj', arb_release=arb_release),
#         expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_tax_silva.prj', arb_release=arb_release)
#     shell:
#         """
#         cd {params.target_dir}/taxonomic
#         fastdb formatted/SILVA_{arb_release}_LSURef_tax_silva {input.lsu_silva_file}
#         fastdb formatted/SILVA_{arb_release}_SSURef_tax_silva {input.ssu_silva_file}
#         """

rule fetch_uniprot_swissprot_db:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/uniprot_sprot'
    shell:
        """
        cd {params.target_dir}/functional
        wget -O uniprot_sprot.gz https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
        gunzip uniprot_sprot.gz
        """

rule make_swissprot_blast_db:
    input:
        config["ref_db_dir"] + '/functional/uniprot_sprot'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.pdb'
    shell:
        """
        cd {params.target_dir}/functional
        makeblastdb -in {input} -dbtype prot -parse_seqids -out formatted/uniprot_sprot
        """

rule make_swissprot_fast_db:
    input:
        config["ref_db_dir"] + '/functional/uniprot_sprot'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/uniprot_sprot.prj'
    shell:
        """
        cd {params.target_dir}/functional
        fastdb -p formatted/uniprot_sprot {input}
        """

        
rule fetch_kegg_uniprot_db:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/kegg-uniprot-2018-12-20'
    shell:
        """
        cd {params.target_dir}/functional
        wget https://ndownloader.figshare.com/files/27422531 -O kegg-uniprot-2018-12-20.gz
        gunzip kegg-uniprot-2018-12-20.gz
        """

rule make_kegg_blast_db:
    input:
        config["ref_db_dir"] + '/functional/kegg-uniprot-2018-12-20'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.pdb'
    shell:
        """
        cd {params.target_dir}/functional
        makeblastdb -in kegg-uniprot-2018-12-20 -dbtype prot -parse_seqids -out formatted/kegg-uniprot-2018-12-20
        """

rule make_kegg_fast_db:
    input:
        config["ref_db_dir"] + '/functional/kegg-uniprot-2018-12-20'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/kegg-uniprot-2018-12-20.prj'
    shell:
        """
        cd {params.target_dir}/functional
        fastdb -p formatted/kegg-uniprot-2018-12-20 {input}
        """

rule fetch_cazy_db:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/cazy-2020-06-01'
    shell:
        """
        cd {params.target_dir}/functional
        wget https://figshare.com/ndownloader/files/30950710 -O cazy-2020-06-01.gz
        gunzip cazy-2020-06-01.gz
        """

rule make_cazy_blast_db:
    input:
        config["ref_db_dir"] + '/functional/cazy-2020-06-01'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.pdb'
    shell:
        """
        cd {params.target_dir}/functional
        makeblastdb -in {input} -dbtype prot -parse_seqids -out formatted/cazy-2020-06-01
        """

rule make_cazy_fast_db:
    input:
        config["ref_db_dir"] + '/functional/cazy-2020-06-01'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/cazy-2020-06-01.prj'
    shell:
        """
        cd {params.target_dir}/functional
        fastdb -p formatted/cazy-2020-06-01 {input}
        """
        
rule fetch_metacyc_db:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/metacyc-2020-08-10'
    shell:
        """
        cd {params.target_dir}/functional
        wget https://ndownloader.figshare.com/files/27419069 -O metacyc-2020-08-10
        """

rule make_metacyc_blast_db:
    input:
        config["ref_db_dir"] + '/functional/metacyc-2020-08-10'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.pdb'
    shell:
        """
        cd {params.target_dir}/functional
        makeblastdb -in {input} -dbtype prot -parse_seqids -out formatted/metacyc-2020-08-10
        """

rule make_metacyc_fast_db:
    input:
        config["ref_db_dir"] + '/functional/metacyc-2020-08-10'
    params:
        target_dir = config['ref_db_dir']
    resources:
        mem_mb = 16000
    output:
        config["ref_db_dir"] + '/functional/formatted/metacyc-2020-08-10.prj'
    shell:
        """
        cd {params.target_dir}/functional
        fastdb -p formatted/metacyc-2020-08-10 {input}
        """


rule fetch_refseq_via_update_blastdb:
    input:
        config["ref_db_dir"] + '/Dsignal'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.26.psq'
    shell:
        """
        cd {params.target_dir}/functional/formatted
        update_blastdb.pl --blastdb_version 5 --decompress refseq_protein
        """


        
rule make_refseq_protein_fast_db:
    input:
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.26.psq'
    params:
        target_dir = config['ref_db_dir']
    resources:
        mem_mb = 40000,
        time_min = '23:0:0'
    output:
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.prj'
    shell:
        """
        blastdbcmd -db {params.target_dir}/functional/formatted/refseq_protein -entry all | fastdb -p {params.target_dir}/functional/formatted/refseq_protein
        """

### Rules for making the *-names.txt files:

rule make_seq_names_file:
    input:
        config['ref_db_dir'] + '{annot_dir}/{db_name}'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '{annot_dir}/formatted/{db_name}-names.txt'
    shell:
        """
        grep "^>" {input} > {output}
        """
        
rule make_refseq_names_file:
    input:
        config["ref_db_dir"] + '/functional/formatted/refseq_protein.26.psq'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '{params.target_dir}/functional/formatted/refseq_protein-names.txt'
    shell:
        """
        blastdbcmd -db {params.target_dir}/functional/formatted/refseq_protein -entry all | grep "^>" > {params.target_dir}/functional/formatted/refseq_protein-names.txt
        """
