## -*- python -*-

#### Snakemake file for MetaPathways

## This is currently used for orchestrating the staging of reference databases used by end-users.
## In the future this will be used to integrate new functionality into MetaPathways.

## Example run: snakemake -p -s Snakefile --use-conda --cores all 

## User-configurations are set in the config YAML file, not in this Snakemake file:
#configfile: "snakemake_config.yaml"

### Local Definitions:
## Database versions:
arb_release = "138.1"
taxonomic_db_names = [
    "SILVA_" + arb_release + "_LSURef_NR99_tax_silva_trunc",
    "SILVA_" + arb_release + "_SSURef_NR99_tax_silva_trunc",
]

script_path = config["script_path"]

# Start off the build
os.system('mkdir -p ' + config["ref_db_dir"])
os.system('touch ' + config["ref_db_dir"] + '/starting_build')

target_ext = "pdb" if config['aligner'] == "blast" else "prj"
functional_db_names = config['functional_db_names'].split(",")
additional_targets = []
if "metacyc" in functional_db_names:
    additional_targets += [
        'functional_categories/MetaCyc-monomer-rxn-pairs.tsv',
        'functional_categories/MetaCyc_PWY_Ontology.tsv',
    ]
if "swissprot" in functional_db_names:
    additional_targets += [
        'functional_categories/EC_map.swissprot.tsv',
    ]
for n in functional_db_names:
    if "uniref" not in n: continue
    additional_targets += [
        f'functional_categories/EC_map.{n}.tsv',
    ]

rule all:
    input:
        expand(config["ref_db_dir"] + '/functional/formatted/{func_db}.' + target_ext, func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/functional/formatted/{func_db}-names.txt', func_db = functional_db_names),
        expand(config['ref_db_dir'] + '/{additional_target}', additional_target = additional_targets),

        expand(config['ref_db_dir'] + '/taxonomic/formatted/{tax_db}-names.txt', tax_db = taxonomic_db_names),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc.ndb', arb_release=arb_release),
        config['ref_db_dir'] + '/ncbi_tree/ncbi_taxonomy_tree.txt'

rule create_dirs_local_files:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config["ref_db_dir"]
    output:
        config["ref_db_dir"] + '/taxonomic/formatted/done'
    shell:
        """
        mkdir -p {params.target_dir}/functional/formatted
        mkdir -p {params.target_dir}/functional_categories
        mkdir -p {params.target_dir}/ncbi_tree
        mkdir -p {params.target_dir}/taxonomic/formatted
        touch {params.target_dir}/taxonomic/formatted/done
        """
        
rule fetch_silva_db:
    input:
        config["ref_db_dir"] + '/taxonomic/formatted/done'
    params:
        target_dir = config["ref_db_dir"],
        arb_release = arb_release
    output:
        lsu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc', arb_release=arb_release),
        ssu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc', arb_release=arb_release)
    shell:
        """
        wget -O {output.lsu_silva_file}.gz https://www.arb-silva.de/fileadmin/silva_databases/release_138_1/Exports/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc.fasta.gz
        wget -O {output.ssu_silva_file}.gz https://www.arb-silva.de/fileadmin/silva_databases/release_138_1/Exports/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc.fasta.gz
        gunzip {output.lsu_silva_file}.gz
        gunzip {output.ssu_silva_file}.gz
        date > {params.target_dir}/functional_categories/SILVA_reldate.txt
        echo "Release: " {arb_release} >> {params.target_dir}/functional_categories/SILVA_reldate.txt
        """

rule make_silva_blast_db:
    input:
        lsu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc', arb_release=arb_release),
        ssu_silva_file = expand(config["ref_db_dir"] + '/taxonomic/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc', arb_release=arb_release)
    params:
        target_dir = config["ref_db_dir"],
        arb_release = arb_release
    output:
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc.ndb', arb_release=arb_release),
        expand(config["ref_db_dir"] + '/taxonomic/formatted/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc.ndb', arb_release=arb_release)
    shell:
        """
        makeblastdb -in {params.target_dir}/taxonomic/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc \
        	-dbtype nucl -parse_seqids -out {params.target_dir}/taxonomic/formatted/SILVA_{arb_release}_LSURef_NR99_tax_silva_trunc
        makeblastdb -in {params.target_dir}/taxonomic/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc \
        	-dbtype nucl -parse_seqids -out {params.target_dir}/taxonomic/formatted/SILVA_{arb_release}_SSURef_NR99_tax_silva_trunc
        """

rule fetch_unirefNN_db:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/uniref{NN}'
    shell:
        """
        wget -O {params.target_dir}/functional/uniref{wildcards.NN}.gz https://ftp.ebi.ac.uk/pub/databases/uniprot/uniref/uniref{wildcards.NN}/uniref{wildcards.NN}.fasta.gz
        gunzip {params.target_dir}/functional//uniref{wildcards.NN}.gz
        wget -O {params.target_dir}/functional_categories/uniref{wildcards.NN}.release_note https://ftp.ebi.ac.uk/pub/databases/uniprot/uniref/uniref{wildcards.NN}/uniref{wildcards.NN}.release_note
        date > {params.target_dir}/functional_categories/uniref{wildcards.NN}_reldate.txt
        cat {params.target_dir}/functional_categories/uniref{wildcards.NN}.release_note >> {params.target_dir}/functional_categories/uniref{wildcards.NN}_reldate.txt
        rm {params.target_dir}/functional_categories/uniref{wildcards.NN}.release_note
        """

rule make_unirefNN_blast_db:
    input:
        config["ref_db_dir"] + '/functional/uniref{NN}'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/uniref{NN}.pdb'
    shell:
        """
        makeblastdb -in {input} -dbtype prot -parse_seqids -out {params.target_dir}/functional/formatted/uniref{wildcards.NN}
        """

rule make_unirefNN_fast_db:
    input:
        config["ref_db_dir"] + '/functional/uniref{NN}'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/uniref{NN}.prj'
    shell:
        """
        fastdb -p {params.target_dir}/functional/formatted/uniref{wildcards.NN} {input}
        """

rule fetch_swissprot_db:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/swissprot'
    shell:
        """
        wget -O {params.target_dir}/functional/swissprot.gz https://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
        gunzip {params.target_dir}/functional/swissprot.gz
        wget -O {params.target_dir}/functional_categories/swissprot_reldate.txt https://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt
        date > {params.target_dir}/functional_categories/SwissProt_reldate.txt
        cat {params.target_dir}/functional_categories/swissprot_reldate.txt >> {params.target_dir}/functional_categories/SwissProt_reldate.txt
        rm {params.target_dir}/functional_categories/swissprot_reldate.txt
        """

rule make_swissprot_blast_db:
    input:
        config["ref_db_dir"] + '/functional/swissprot'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/swissprot.pdb'
    shell:
        """
        makeblastdb -in {input} -dbtype prot -parse_seqids -out {params.target_dir}/functional/formatted/swissprot
        """

rule make_swissprot_fast_db:
    input:
        config["ref_db_dir"] + '/functional/swissprot'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/swissprot.prj'
    shell:
        """
        fastdb -p {params.target_dir}/functional/formatted/swissprot {input}
        """

rule fetch_cazy_db:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/cazy'
    shell:
        """
        wget -O {params.target_dir}/functional/cazy https://bcb.unl.edu/dbCAN2/download/Databases/V12/CAZyDB.07262023.fa
        date > {params.target_dir}/functional_categories/CAZyDB_reldate.txt
        echo "Release: V12_07262023" >> {params.target_dir}/functional_categories/CAZyDB_reldate.txt
        """

rule make_cazy_blast_db:
    input:
        config["ref_db_dir"] + '/functional/cazy'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/cazy.pdb'
    shell:
        """
        makeblastdb -in {input} -dbtype prot -parse_seqids -out {params.target_dir}/functional/formatted/cazy
        """

rule make_cazy_fast_db:
    input:
        config["ref_db_dir"] + '/functional/cazy'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/cazy.prj'
    shell:
        """
        fastdb -p {params.target_dir}/functional/formatted/cazy {input}
        """
       
rule fetch_metacyc_db:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config['ref_db_dir'],
    output:
        config["ref_db_dir"] + '/functional/metacyc'
    shell:
        """                                  
        wget --netrc=on -O {params.target_dir}/functional/meta.tar.gz https://brg-files.ai.sri.com/subscription/dist/flatfiles-52983746/meta.tar.gz
        tar -xvzf {params.target_dir}/functional/meta.tar.gz -C {params.target_dir}/functional/
        cp {params.target_dir}/functional/*/data/protseq.fsa {params.target_dir}/functional/metacyc
        version=$(echo {params.target_dir}/functional/*/data/protseq.fsa | rev | cut -d'/' -f3 | rev)
        date > {params.target_dir}/functional_categories/MetaCyc_reldate.txt
        echo "Release: " $version >> {params.target_dir}/functional_categories/MetaCyc_reldate.txt
        """

rule make_metacyc_blast_db:
    input:
        config["ref_db_dir"] + '/functional/metacyc'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/metacyc.pdb'
    shell:
        """
        makeblastdb -in {input} -dbtype prot -parse_seqids -out {params.target_dir}/functional/formatted/metacyc
        """

rule make_metacyc_fast_db:
    input:
        config["ref_db_dir"] + '/functional/metacyc'
    params:
        target_dir = config['ref_db_dir']
    output:
        config["ref_db_dir"] + '/functional/formatted/metacyc.prj'
    shell:
        """
        fastdb -p {params.target_dir}/functional/formatted/metacyc {input}
        """

### Rule for making the *-names.txt files:
rule make_seq_names_file:
    input:
        config['ref_db_dir'] + '{annot_dir}/{db_name}'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '{annot_dir}/formatted/{db_name}-names.txt'
    shell:
        """
        grep "^>" {input} > {output}
        """

### Rule for mapping MetaCyc Monomers to Reaction IDs:
rule mono_2_rxn:
    input:
        config["ref_db_dir"] + '/functional/metacyc'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '/functional_categories/MetaCyc-monomer-rxn-pairs.tsv'
    shell:
        """
        base=$(dirname $(ls {params.target_dir}/functional/*/data/protseq.fsa))
	    python {script_path}/metacyc_mapping_build.py $base
	    cp $base/MetaCyc-*.tsv {params.target_dir}/functional_categories/
        """

### Rule for building the MetaCyc Ontology:
rule pwy_2_ont:
    input:
        config["ref_db_dir"] + '/functional/metacyc'
    params:
        target_dir = config['ref_db_dir'],
        output_dir = config['ref_db_dir'] + '/functional_categories/',
    output:
        output_file = config['ref_db_dir'] + '/functional_categories/MetaCyc_PWY_Ontology.tsv'
    shell:
        """
        base=$(dirname $(ls {params.target_dir}/functional/*/data/protseq.fsa))
	    python {script_path}/metacyc_build_ont.py $base {params.output_dir}
        """

rule fetch_ec_db:
    input:
        config["ref_db_dir"] + '/starting_build'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '/functional_categories/enzyme.dat'
    shell:
        """
        wget -O {params.target_dir}/functional_categories/enzyme.dat https://ftp.expasy.org/databases/enzyme/enzyme.dat
        wget -O {params.target_dir}/functional_categories/enzclass.txt https://ftp.expasy.org/databases/enzyme/enzclass.txt
        date > {params.target_dir}/functional_categories/Expasy_reldate.txt
        grep '^Release: ' {params.target_dir}/functional_categories/enzclass.txt >> {params.target_dir}/functional_categories/Expasy_reldate.txt
        rm {params.target_dir}/functional_categories/enzclass.txt
        """

### Rule for mapping SwissProt to EC numbers:
rule swiss_2_ec:
    input:
        config["ref_db_dir"] + '/functional/swissprot',
        config['ref_db_dir'] + '/functional_categories/enzyme.dat'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '/functional_categories/EC_map.swissprot.tsv'
    shell:
        """
        python {script_path}/swissprot_mapper.py {params.target_dir}/functional_categories/enzyme.dat {params.target_dir}/functional_categories
        """

### Rule for mapping uniref{wildcards.NN} to EC numbers:
rule unirefNN_2_ec:
    input:
        config["ref_db_dir"] + '/functional/uniref{NN}',
        config['ref_db_dir'] + '/functional_categories/enzyme.dat'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '/functional_categories/EC_map.uniref{NN}.tsv'
    shell:
        """
        wget -O {params.target_dir}/functional_categories/idmapping.dat.gz https://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping.dat.gz
        zgrep 'UniRef{wildcards.NN}_' {params.target_dir}/functional_categories/idmapping.dat.gz > {params.target_dir}/functional_categories/uniref{wildcards.NN}_idmapping.dat
        python {script_path}/uniref{wildcards.NN}_mapper.py {params.target_dir}/functional_categories/enzyme.dat {params.target_dir}/functional_categories
        """

### Rule for building taxmapping for LCA:
rule build_taxmap:
    input:
        config["ref_db_dir"] + '/taxonomic/formatted/done'
    params:
        target_dir = config['ref_db_dir']
    output:
        config['ref_db_dir'] + '/ncbi_tree/ncbi_taxonomy_tree.txt'
    shell:
        """
        wget -O {params.target_dir}/ncbi_tree/new_taxdump.tar.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
        tar xvzf {params.target_dir}/ncbi_tree/new_taxdump.tar.gz -C {params.target_dir}/ncbi_tree/
        python {script_path}/taxmap_build.py {params.target_dir}/ncbi_tree/
        """


