#!/usr/bin/env python3
"""Generate the GitHub CLI reference from the installed source parser help."""
import argparse
import os
from pathlib import Path
import subprocess
import sys

ROOT=Path(__file__).resolve().parents[1]
COMMANDS=('prepare_test','run','analysis_wf','build_db','mag_split','build_pt','ptools','report')


def render():
    env=dict(os.environ, PYTHONPATH=str(ROOT), COLUMNS='100')
    text='# Complete CLI reference\n\n[User guide](index.md) · [Workflow guide](workflow.md)\n\n'
    text+='Generated by `python scripts/generate_cli_docs.py`. Run `metapathways COMMAND --help` for the help of your installed revision.\n\n'
    for command in COMMANDS:
        code='import sys; from metapathways.pipeline import main; sys.argv=["metapathways"]+sys.argv[1:]; main()'
        result=subprocess.run([sys.executable,'-c',code,command,'--help'],cwd=ROOT,env=env,check=True,text=True,capture_output=True)
        text+=f'## {command}\n\n```text\n{result.stdout.rstrip()}\n```\n\n'
    return '\n'.join(line.rstrip() for line in text.splitlines()).rstrip() + '\n'


def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    target=ROOT/'docs/cli-reference.md';expected=render()
    if args.check:
        if not target.is_file() or target.read_text()!=expected:
            raise SystemExit('CLI reference is stale; run python scripts/generate_cli_docs.py')
        print('CLI reference matches current parser help.')
    else:
        target.write_text(expected)

if __name__=='__main__':main()
